//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.WebApi.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionInformation
    {
        public AuctionInformation()
        {
            this.BidParticipantInformations = new HashSet<BidParticipantInformation>();
        }
    
        public int AuctionInformationId { get; set; }
        public int ProductId { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime BidStartDateTime { get; set; }
        public System.DateTime BidEndDateTime { get; set; }
        public string BidDescription { get; set; }
        public decimal BidBasePrice { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<BidParticipantInformation> BidParticipantInformations { get; set; }
    }
}
