//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.WebApi.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BidParticipantInformation
    {
        public int BidParticipantInformationId { get; set; }
        public int UserId { get; set; }
        public int AuctionInformationId { get; set; }
        public decimal BidPrice { get; set; }
        public System.DateTime BidCreationDateTime { get; set; }
    
        public virtual AuctionInformation AuctionInformation { get; set; }
        public virtual User User { get; set; }
    }
}
