//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.WebApi.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.AuctionInformations = new HashSet<AuctionInformation>();
        }
    
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImageUrl { get; set; }
        public int ProductTypeId { get; set; }
        public Nullable<bool> ProductStatus { get; set; }
    
        public virtual ICollection<AuctionInformation> AuctionInformations { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
